### ISSUE TITLE
Insert bezier point - Blender 2.8 compatibility

### ISSUE THREAD

**Issue by ghost** [LeanderSilur/Blender-Tools#1]
Insert bezier point doesn't work in blender 2.80.75 :(

![image](https://user-images.githubusercontent.com/17996249/63071369-b0a8e800-bf27-11e9-8d99-90248be5c925.png)

**Comment by EdyJ** [comment]
I've been able to update it to work in 2.80.75:
https://pastebin.com/h3E5HJmS

Only no handler is drawn in the viewport, but the numeric position in the spline is displayed. Drawing the handler requires a more profound update as the bgl modude has been deprecated. That part should be rewritten to use the 2.8 gpu module:

https://docs.blender.org/api/blender2.8/gpu.html

**Comment by calvertcreates** [comment]
I am able to add new points in 2.80 with your edit but I don't see them visually to know specifically where the point is. 

![2019-11-25_15-56-21](https://user-images.githubusercontent.com/9643084/69577366-2fd4a000-0f9c-11ea-8f61-70c53f45fd3d.gif)

**Comment by AndrewYY** [comment]
I have done the full upgrade including UI changes and submitted a pull request #2

**Comment by LeanderSilur** [comment]
@AndrewYY Fantastic, it looks great. I will review it and merge it tomorrow. Would you like your full name to be added to the author field? Or should I just credit your github account in the stackexchange post?

**Comment by AndrewYY** [comment]
@LeanderSilur a shoutout on stackexchange would be kind :) I appreciate your writeup, and updated the tool because I was really missing the feature! Cheers, and happy blendering.

**Comment by LeanderSilur** [comment]
Fixed thanks to AndrewYY in [commit](https://github.com/LeanderSilur/Blender-Tools/commit/56021b13550d6149e954bb1625cd761ef9321f17).

[Release v0.9](https://github.com/LeanderSilur/Blender-Tools/releases/tag/curve_edit_tools) is for 2.8x.

**Comment by LeanderSilur** [comment]
@EdyJ @helloprivet Notifying you just in case =)

**Comment by EdyJ** [comment]
Thank you!
