### ISSUE TITLE
Issues with Blender 3.2

### ISSUE THREAD

**Issue by knotimpressed** [LeanderSilur/Blender-Tools#11]
As far as I can see, this addon needs to be updated to work with Blender 3.X (in my case 3.2).

I really really like this addon and it helps me a lot with curves, so I hope it can be updated to work with current versions. I know python but not the ins and outs of addon creation, otherwise I'd update this. 

I did try crudely updating __init__.py to contain 
`"version": (1, 3, 3),
"blender": (3, 1, 0),`
but this didn't work (the addon doesn't even appear in the list, although it does install).

Thank you so much for making this addon!

**Comment by LeanderSilur** [comment]
For some reason, the zip didn't include a folder. [Please try again.](https://github.com/LeanderSilur/Blender-Tools/releases/tag/curve_edit_tools)

**Comment by knotimpressed** [comment]
Huh, I responded over email but it didn't show up; it works now so I'll mark it as closed. Thank you so much, again I'm so glad that you made this addon!

**Comment by knotimpressed** [comment]
I see your updated comment now, I will try and let you know. Thank you!

**Comment by knotimpressed** [comment]
So sorry, I meant curve edit tools. I didn’t realize all the issues were
also lumped together.

Is updating curve edit tools possible?
