### ISSUE TITLE
Curve edit tools error message in blender 3.6 and issues with 4.0 ...

### ISSUE THREAD

**Issue by nurb2kea** [LeanderSilur/Blender-Tools#12]
Hi,

just came across the 3.6 and 4.0 build of blender.
3.6 will be released this week, so I thought it's maybe a good idea to let you know about.

![Screenshot 2023-06-26 at 1 25 53 am](https://github.com/LeanderSilur/Blender-Tools/assets/57676085/e01e3baf-36e1-4b5e-a320-f0b88ac291f7)
![Screenshot 2023-06-26 at 1 26 46 am](https://github.com/LeanderSilur/Blender-Tools/assets/57676085/3510f3d6-fa6c-4e49-8ff8-0ba64707b417)
![Screenshot 2023-06-26 at 1 27 40 am](https://github.com/LeanderSilur/Blender-Tools/assets/57676085/0d71f27a-6194-4463-9f5e-c7c3e2bbfa5c)

Here some info on that by the dev's:
The blender dev’s reccomended to ask [https://projects.blender.org/mano-wii ](https://projects.blender.org/mano-wii)
and look at this case to get more info on this to fix addons.

EDIT: More info !

There are two reasons why shaders needs to be ported:

Addon still uses bgl that call OpenGL calls directly.
Shader don’t use gpu.types.ShaderCreateInfo to support cross platform source generation.
These structures have already been in place for some time, and we communicated that addon developers should use this new API. It is sadly common for developers to only port to newer API’s when it makes sense for them.

In this case it looks like he hasn’t ported his shaders to use gpu.types.ShaderCreateInfo as described on [https://docs.blender.org/api/current/gpu.html 2](https://docs.blender.org/api/current/gpu.html). If someone requires some help they can get in contact with the Eevee/viewport module at blender.chat or in the python channel. I am happy to help out there.

That should help to get rid of the error message (see the image up top)
For blender 4.0 and the addon not getting registered correct and can't be called via operator search, I don't have any info to fix.

Anyways, would be nice to keep curve edit tools alive !

**Comment by Kickflipkid687** [comment]
I tried to use in Blender 4.0 now as well, and was having an error :( 

![1C005C0F-8B09-43CD-BD6F-B6FB014AB36B](https://github.com/LeanderSilur/Blender-Tools/assets/68572762/23e20554-5bd2-4b15-ab44-8bfb41bdc14a)

**Comment by LeanderSilur** [comment]
@nurb2kea @Kickflipkid687 Please check the [.zip](https://github.com/LeanderSilur/Blender-Tools/releases/tag/curve_edit_tools_v0.9.3) in the new release. Thank you.
