### ISSUE TITLE
Insert bezier point - Blender 2.9 compatibility

### ISSUE THREAD

**Issue by Kickflipkid687** [LeanderSilur/Blender-Tools#3]
Hello!

I was testing this addon in 2.9 Alpha today and got this error.   I can try installing into 2.83.13 and see if i get the same issue or not.   But figured I should/could mention this in preparation for the 2.9 release in a month.  

Looks like it was hitting the issue on line 142  (get_2d_closest_bezier)

I was trying to insert a point in Edit Mode, on a single Bezier Curve, in Right Orthographic View.  

Thank you!  This addon looks very nice!

![2d_curve_error](https://user-images.githubusercontent.com/68572762/87999962-4098cf80-cab1-11ea-931a-93d02cdb802c.png)

**Comment by LeanderSilur** [comment]
Thanks for testing. Are you using the newest Blender 2.9? I can't reproduce the problem. Please list some clear steps.

I just downloaded Blender *2.90.0 Alpha* (731d9f0bfa40) [master] and installed the released zip without errors.

**Comment by Kickflipkid687** [comment]
Ah, ok now it works.  Not sure what the issue was.

Although I found another bug, unless it's by design.  If I center the Pivot to the object Center and not leave it at 0,0,0 the new point is way off from the object/not in the proper object space any longer.  

If I have to work with the pivot at 0,0,0 at first, that's OK.  

Thank you!

**Comment by LeanderSilur** [comment]
Cool. Incidentically, I found and [opened](https://github.com/LeanderSilur/Blender-Tools/issues/4) the other bug you describe. Will probably fix that one soon, as it sounds fairly simple.

For now, you could simply create a duplicate linked copy of your curve object (Alt D) and clear its transform (Alt G, Alt R, Alt S). Work with the duplicate curve at the origin (0, 0, 0) and delete the object once you're done. The original curve will update as well after the edits, if the share the same curve-datablock.

**Comment by Kickflipkid687** [comment]
Oh yeah, that would work too.  Yeah i was gonna say, I just saw the same error again when my pivot point was way off or something/ transforms not reset.

**Comment by LeanderSilur** [comment]
I believe, the other fix would also solve this Problem then.

However, if you could manage to document the steps to reproduce this error message, please post them here.

**Comment by Kickflipkid687** [comment]
Hmm, is a weird one.   

 - If i create a new curve using Flexi Bezier  Addon, the pivot is not at (0,0,0), so the insert point is offset from the object, but no error.   Flexi centers the pivot to the new Curve.  

- Trying to insert a point into an existing bezier curve (originally created with Flexi) it sometimes gives that error.  But again, the pivot was not at 0,0,0.    Scale is 1,1,1 however, in both cases.   

- When pivot is reset to 0,0,0 in any case, all is well.  

So yes, I think if the issue is fixed with the pivot being at 0,0,0 or offsetting the matrix/however that has to work, to fix that issue, that may solve both.

**Comment by LeanderSilur** [comment]
@Kickflipkid687 Checkout the latest [release](https://github.com/LeanderSilur/Blender-Tools/releases/tag/curve_edit_tools) and report back if the problem still persists.

**Comment by Kickflipkid687** [comment]
Thank you! Seems to work great now!
