### ISSUE TITLE
simbones - no module named 'scipy'

### ISSUE THREAD

**Issue by mond-cz** [LeanderSilur/Blender-Tools#5]
May I ask you to confirm your script should work in blender 2.82, 2.83 or 2.9x. 
I cant enable it in UserPref.  Thank you 

(vklidu)

![image](https://user-images.githubusercontent.com/649050/88486905-5a3e8900-cf81-11ea-80d7-e7141f3762fa.png)

**Comment by LeanderSilur** [comment]
Currently, you have to manually install the scipy module before enabling the addon. I added some steps on [installing scipy](https://github.com/LeanderSilur/Blender-Tools/tree/master/simbones#dependencies) for Blenders python.

I have not researched on how to install a python module through an addon yet.

I'm using Blender 2.83.

**Comment by mond-cz** [comment]
Ah, OK, thank you for more details.
I could read error at the end to ask better :)

**Comment by LeanderSilur** [comment]
Fixed by [Travis](https://github.com/LeanderSilur/Blender-Tools/pull/8).
