### ISSUE TITLE
Simbones - Presets and starting values

### ISSUE THREAD

**Issue by notDimm** [LeanderSilur/Blender-Tools#6]
i wanted to start by saying that simbones is the most reliable addon to give bones physics since it works 100% of the time unlike the other alternatives, so i'm really happy with this find, the only thing i feel like is missing is the ability to save presets for the simulation settings (i think blender has functions to do this), and be able to save new defaults might be helpful too since, for me at least, i never use the default settings and 90% of the time i want to change it to the same ones

**Comment by LeanderSilur** [comment]
@2Dimm That sounds like a very useful feature. I added in in [commit](https://github.com/LeanderSilur/Blender-Tools/commit/b85429951290b04404e9c21bc3cc61dc0aea561c). You can test the [v1.0.1 release](https://github.com/LeanderSilur/Blender-Tools/releases/tag/simbones) and open up some issues in case I broke something.

Also improved default hotkeys and documentation a tiny bit.
