### ISSUE TITLE
Simbones - Scene properties preset

### ISSUE THREAD

**Issue by notDimm** [LeanderSilur/Blender-Tools#7]
thank you for releasing the new preset feature so quickly! it works perfectly on the bone properties tab, but the preset features on the scene property tab completely dont work, creating a new preset gives the error "name 'world' is not defined", selecting a preset just does nothing and trying to remove presets says the file being used by another process

**Comment by LeanderSilur** [comment]
That was a typo, I [updated v1.0.1](https://github.com/LeanderSilur/Blender-Tools/releases/tag/simbones). Could you try again?

**Comment by LeanderSilur** [comment]
And if you have trouble deleting old preset files, try shutting down Blender and related processes, launch the file explorer in administrative mode and go to:

System | Path
--|--
Linux | ~/.config/blender/2.81/scripts/presets/simbone/
Mac | /Users/{user}/Library/Application/Support/Blender/2.81/scripts/presets/simbone/
Windows | C:\Documents and Settings\%username%\Application Data\Blender Foundation\Blender\2.81\scripts\presets\simbone\

There you should be able to delete any rogue/left-over preset files.

**Comment by notDimm** [comment]
everything works perfectly now, thanks!
